apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deployment
 namespace: nginx
spec:
 selector:
   matchLabels:
    type: backend
 replicas: 2
 template:
   metadata:
     labels:
       type: backend
   spec:
    containers:
    - name: backend
      image: dasadanan/test:backlatest
      envFrom:
      ports:
      - containerPort: 8000
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]