apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deployment
 namespace: nginx
spec:
 selector:
   matchLabels:
    type: backend
 replicas: 1
 template:
   metadata:
     labels:
       type: backend
       app: backend
       version: vlatest
   spec:
    containers:
    - name: backend
      image: dasadanan/test:back140
      envFrom:
        - configMapRef:
            name: mysql-cm
        - secretRef:
            name: mysql-sec
      command: ["pip"]
      args: ["install", "pymysql"]
      ports:
      - containerPort: 8000
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m